# Generated by Django 4.0.10 on 2024-05-18 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_category_userprofile_height_userprofile_weight_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='max_bmi',
            field=models.FloatField(default=50),
        ),
        migrations.AddField(
            model_name='recipe',
            name='min_bmi',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='workout',
            name='max_bmi',
            field=models.FloatField(default=50),
        ),
        migrations.AddField(
            model_name='workout',
            name='min_bmi',
            field=models.FloatField(default=0),
        ),
    ]
