# Generated by Django 4.0.10 on 2024-05-22 21:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_uploadedfile_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Recipe',
        ),
    ]
