# Generated by Django 4.0.10 on 2024-05-22 21:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0006_delete_recipe'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Workout',
        ),
    ]
