# Generated by Django 4.0.10 on 2024-05-22 21:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0007_delete_workout'),
    ]

    operations = [
        migrations.CreateModel(
            name='Workout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('note', models.TextField()),
                ('pazartesi', models.TextField()),
                ('salı', models.TextField()),
                ('çarşamba', models.TextField()),
                ('perşembe', models.TextField()),
                ('cuma', models.TextField()),
                ('cumartesi', models.TextField()),
                ('pazar', models.TextField()),
                ('min_bmi', models.FloatField(default=0)),
                ('max_bmi', models.FloatField(default=50)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.category')),
            ],
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('sabah', models.TextField()),
                ('ara_ogun_1', models.TextField()),
                ('ogle', models.TextField()),
                ('ara_ogun_2', models.TextField()),
                ('aksam', models.TextField()),
                ('gece', models.TextField()),
                ('notlar', models.TextField()),
                ('min_bmi', models.FloatField(default=0)),
                ('max_bmi', models.FloatField(default=50)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.category')),
            ],
        ),
    ]
